name: Deployment

# Triggered manually
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get master
      - uses: actions/checkout@v1
        with:
          ref: master

      - name: Get deployment
        uses: actions/checkout@v1
        with:
          ref: deployment

      - name: Merge master -> deployment
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: deployment
          github_token: ${{ secrets.GITHUB_TOKEN }}
