name: Deployment

# Triggered manually
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get project version
        run: |
          [xml]$xml = Get-Content .\Packager\Packager.csproj
          $version = $xml.Project.PropertyGroup.Version
          echo "V=v$version" >> $GITHUB_ENV
          echo "Deploying v$version ..."
          echo "Deploying $V ..."

      - name: Update deployment branch
        run: echo "Deploying $V ..."
