name: Deployment

# Triggered manually
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: windows-latest
    
    steps:
      # Checks-out master (to be able to merge it)
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      # Checks-out deployment
      - uses: actions/checkout@v2
        with:
          ref: 'deployment'

      - name: Execute deployment
        run: |
          [xml]$xml = Get-Content .\Packager\Packager.csproj
          $version = $xml.Project.PropertyGroup.Version
          set VERSION v$version
          echo "Deploying $VERSION ..."
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@githubaction.io
          git merge master -m "$VERSION"
          git push
