name: Deployment

# Triggered manually
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: windows-latest
    
    steps:
      # Get repositiory
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@githubaction.io
          git checkout master
          git pull
          git checkout deployment
          git pull

      - name: Deploy
        run: |
          git status
          git checkout master
          [xml]$xml = Get-Content .\Packager\Packager.csproj
          $version = $xml.Project.PropertyGroup.Version
          set VERSION v$version
          echo "Deploying $VERSION ..."
          git checkout deployment
          ls
          git rebase origin/master
          git status
          git commit --alow-empty -m "$VERSION"
          git push
