name: Deployment

# Triggered manually
on: workflow_dispatch

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Execute deployment
        run: |
          [xml]$xml = Get-Content .\Packager\Packager.csproj
          $version = $xml.Project.PropertyGroup.Version
          set VERSION v$version
          echo "Deploying $VERSION ..."
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@githubaction.io
          git commit --allow-empty -m "$VERSION"
          git fetch . master:deployment
          git push origin deployment
